class_name UpgradeConstants
extends RefCounted

enum TYPE {
		UNDEFINED,
		DAMAGE,
		MINING_SPEED,
		HEALTH,
		DURABILITY,
		JUMP_HEIGHT,
		WORLD_SIZE_WIDTH,
		WORLD_SIZE_HEIGHT}

enum VALUE_TYPE {GENERIC, PERCENTAGE}

const MINING_SPEED_SCALE_BASE: float = 1.0
const DAMAGE_BASE: float = 25.0
const HEALTH_BASE: float = 100.0
const JUMP_HEIGHT_BASE: float = 200.0
const WORLD_SIZE_WIDTH_HEIGHT_BASE: float = 85.0
